on:
  push:
    branches:
      - thesis
  pull_request:
    branches:
      - thesis

jobs:
  typecheck:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Typechecking
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2
      - name: Run Agda
        id: typecheck
        uses: ayberkt/agda-github-action@v3.4
        with:
          main-file: index.lagda.md
          source-dir: source/TWA/Thesis/
          unsafe: true
          css: https://www.cs.bham.ac.uk/~txw467/tychonoff/Agda.css
      - name: Deploy HTML to branch
        uses: s0/git-publish-subdir-action@develop
        if: github.event_name != 'pull_request'
        env:
          REPO: self
          BRANCH: html
          FOLDER: source/TWA/Thesis/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload HTML as artifact
        id: html-upload
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: source/TWA/Thesis/html